#!/bin/bash

CMAKE_GENERATOR="Unix Makefiles"
declare -a CMAKE_CONFIG_ARGS

CMAKE_CONFIG_ARGS+=(-DCMAKE_BUILD_TYPE:STRING=Release)
CMAKE_CONFIG_ARGS+=(-DCMAKE_PREFIX_PATH:PATH=${PREFIX})
CMAKE_CONFIG_ARGS+=(-DCMAKE_FIND_ROOT_PATH:PATH=${PREFIX})
CMAKE_CONFIG_ARGS+=(-DCMAKE_INSTALL_PREFIX:PATH=${PREFIX})
CMAKE_CONFIG_ARGS+=(-DCMAKE_INSTALL_RPATH:PATH=${PREFIX}/lib)
CMAKE_CONFIG_ARGS+=(-DBUILD_SHARED_LIBS:BOOL=ON)
CMAKE_CONFIG_ARGS+=(-DPython3_EXECUTABLE=${PYTHON})
CMAKE_CONFIG_ARGS+=(-DCC3D_EXT_NAME:STRING=cc3dext)
if [[ $(uname) == Darwin ]]; then
    CMAKE_CONFIG_ARGS+=(-DCMAKE_OSX_SYSROOT=${CONDA_BUILD_SYSROOT})
fi

mkdir build
cd build

cmake -G "${CMAKE_GENERATOR}" \ \
      "${CMAKE_CONFIG_ARGS[@]}" \
      "${SRC_DIR}/cc3dext/MaBoSS"
make -j${CPU_COUNT} VERBOSE=1
make install
