CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk # [osx]

c_compiler:
  - gcc # [linux]
  - clang # [osx]
  - m2w64-toolchain # [win]
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
  - m2w64-toolchain # [win]
